### PR TITLE
Add Codecov integration

### PR DESCRIPTION
**Pull request by stevepeak**
> re @trevorah, @mydigitalself 

Adding integration with Codecov for coverage changes.

### CODE REVIEW

**Comment by stevepeak** [comment]
I'm not sure on what the message will state yet. I'll be working on that shortly. Thanks

**Comment by trevorah** [comment]
Any progress on this @stevepeak?

**Comment by stevepeak** [comment]
Hey @trevorah thanks for reaching out. Just posted a couple changes to the payload. Otherwise we are a go!

I'll need to update the UI to fully enable the feature. I would like to flag some customers through to make sure it works first.

**Comment by trevorah** [comment]
Cool, give me a shout when things are ready to merge or if you need a hand.

**Comment by stevepeak** [comment]
Hey @trevorah I believe we are a go! I'll enable this feature in our backend. Thanks!

**Comment by trevorah** [comment]
Thanks @stevepeak, I'll let you know once this is live.

**Comment by stevepeak** [comment]
This is live :) Thank you! Let me know when you deploy.

**Comment by trevorah** [comment]
Deployment has now reached production!

**Comment by stevepeak** [comment]
Thank you! I'll give it a spin now :+1:

**Pull request merged**
