### PR TITLE
Minimal Open Collective service for Gitter

### PR DESCRIPTION
**Pull request by sedubois**
Just a minimal service for opencollective.com notifications. Let me know if there would be any question!

I tested this with a locally running instance of our OpenCollective backend (whose software will be open sourced very soon, BTW).

### CODE REVIEW

**Comment by trevorah** [comment]
Thanks @sedubois! Sorry about the delay, I'll merge this in now.

**Comment by sedubois** [comment]
Any estimate when this will be available on gitter.im?

**Comment by MadLittleMods** [comment]
@sedubois Probably a couple days. Our build is currently blocked but we plan to cut some releases this week.

**Comment by trevorah** [comment]
@sedubois it should be live now!

**Comment by sedubois** [comment]
@trevorah thanks! Any reason why the OpenCollective logo isn't displayed in the list of integrations on Gitter.im? It appeared in my local tests

**Comment by trevorah** [comment]
@sedubois thats down to the styling of the buttons right now. The button's title is so long that it hides the logo from view.

**Pull request merged**
