### PR TITLE
Docker Hub improvements

### PR DESCRIPTION
**Pull request by md5**
The Docker Hub webhook payload has an `images` field that can be either null or an array of image ids that were pushed. In the case of an automated build with N tags, the webhook will receive N-1 notifications with `images=null` and a final notification with an N element array.

The new notification logic is:

* `images=null || images.length === 0`: No notification
* `images.length === 1`: Notification including short id of pushed image
* `else` (`images.length > 1`): Notification including number of images pushed

I also added a link to Docker Hub in the `instructions.md`.

### CODE REVIEW

**Comment by trevorah** [comment]
Thanks for the pr @md5, im getting this live now.

**Comment by md5** [comment]
:metal:

**Comment by trevorah** [comment]
It should be live now :tada:

**Comment by md5** [comment]
I guess I need to get to work pushing some Docker images...

**Pull request merged**
