### PR TITLE
GoCD webhook integration

### PR DESCRIPTION
**Pull request by bdpiparva**

### CODE REVIEW

**Comment by bdpiparva** [comment]
Yes I have tested it on go server, Gitter plugin is still in beta.

**Comment by suprememoocow** [comment]
Thank you for this @bdpiparva 👍

**Comment by bdpiparva** [comment]
Thank you guys @suprememoocow , @suprememoocow, @MadLittleMods to make it really quick, I am waiting for gitter release 👍 .

**Comment by trevorah** [comment]
@bdpiparva it should be there in the next 10 mins or so.

**Comment by bdpiparva** [comment]
Coool

**Pull request merged**
