### PR TITLE
Adding integration for Snap Ci

### PR DESCRIPTION
**Pull request by mihirk**
Updating Gitignore to account for Intellij Idea projects

### CODE REVIEW

**Comment by mihirk** [comment]
Sorry checked in some ES6 code by accident. Fixed it to ES5 in the next commit.

**Comment by trevorah** [comment]
Looks good @mihirk! I have three points:

1. The message itself is markdown, so instead of
  ```md
  Test Stage for build https://snap-ci.com/ExampleProject/example-client/branch/branchname Failed
  ```
  you could do
  ```md
  Test Stage for ExampleProject/example-client [Failed](https://snap-ci.com/ExampleProject/example-client/branch/branchname)
  ```
  which is easier for users to read.

2. Its not worth alerting the user about an unknown state. You can return `undefined` and nothing will be added to the activity feed.
3. Concatenating strings will be more efficient than calling `.replace()` multiple times, but thats no big deal if you leave that in.

**Comment by mihirk** [comment]
Cool I will incorporate those changes.

**Comment by mihirk** [comment]
Should I squash the commits as well?

**Comment by trevorah** [comment]
Thanks @mihirk! This should be live next week.

**Pull request merged**
