### PR TITLE
Update GitLab logos

### PR DESCRIPTION
**Pull request by mike-koch**
This PR updates the logo used for GitLab integration to the new logo that was rolled out in May of last year.

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@mike-koch Can you make your membership to `gitlabHQ` public? https://github.com/orgs/gitlabhq/people

**Comment by mike-koch** [comment]
@MadLittleMods I have never worked for nor contributed to GitLab itself; I am just a user.

**Comment by MadLittleMods** [comment]
This looks just fine. I asked here if anyone wanted to sanction this though, :point_up: [April 17, 2016 6:24 PM](https://gitter.im/gitlabhq/gitlabhq?at=57141b123066f78f385dee95)

**Comment by trevorah** [comment]
Looks fine to me

**Comment by trevorah** [comment]
Thanks @mike-koch, it should go live in the next release.

**Pull request merged**
