### PR TITLE
Add gitbook service

### PR DESCRIPTION
**Pull request by SamyPesse**
We introduced webhooks yesterday: https://www.gitbook.com/blog/features/slack
And some users ask us for an integration with Gitter (https://twitter.com/prudhomm/status/663924795780763648).

I tested with a running instance of gitbook.com:

screen shot 2015-11-10 at 11 58 14

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@SamyPesse One of the tests seems to be hitting a snag:

> GitBook publish should generate a publish event:
> ```
>     TypeError: Cannot read property 'message' of undefined
>       at Context.<anonymous> (/home/travis/build/gitterHQ/services/lib/gitbook/test/index.js:12:26)
>       at callFn (/home/travis/build/gitterHQ/services/node_modules/mocha/lib/runnable.js:250:21)
>       at Test.Runnable.run (/home/travis/build/gitterHQ/services/node_modules/mocha/lib/runnable.js:243:7)
>       at Runner.runTest (/home/travis/build/gitterHQ/services/node_modules/mocha/lib/runner.js:373:10)
>       at /home/travis/build/gitterHQ/services/node_modules/mocha/lib/runner.js:451:12
>       at next (/home/travis/build/gitterHQ/services/node_modules/mocha/lib/runner.js:298:14)
>       at /home/travis/build/gitterHQ/services/node_modules/mocha/lib/runner.js:308:7
>       at next (/home/travis/build/gitterHQ/services/node_modules/mocha/lib/runner.js:246:23)
>       at Object._onImmediate (/home/travis/build/gitterHQ/services/node_modules/mocha/lib/runner.js:275:5)
>       at processImmediate [as _immediateCallback] (timers.js:363:15)
> ```

**Comment by SamyPesse** [comment]
@MadLittleMods Fixed, Sorry I forgot to adapt tests after my last commit.

**Comment by SamyPesse** [comment]
Any update?

**Comment by trevorah** [comment]
Thanks @SamyPesse!

This should be live in the next few days. I'll give you a shout when it reaches production.

**Comment by trevorah** [comment]
@SamyPesse it's live :tada:

**Comment by SamyPesse** [comment]
Awesome! Thanks :beers:

**Pull request merged**
