### PR TITLE
Gitlab Enhancements - Adds comments. Enhances issue and merge request events.

### PR DESCRIPTION
**Pull request by scriptnull**
This PR
- finishes some parts of  https://github.com/gitterHQ/services/issues/77
- fixes https://github.com/gitterHQ/gitter/issues/1385

Here are the results got after checking against a webhook directly from gitlab project.

### Issue open : 
image

### Issue close :
image

### Issue reopen :
image

### Issue comment : 
image

### Merge request open : 
image

### Merge request close :
image

### Merge request reopen :
image

### Merge request comment :
image

### CODE REVIEW

**Comment by trevorah** [comment]
Thanks @scriptnull!

**Comment by trevorah** [comment]
As this doesnt change any of the web assets, I should be able to get this live pretty soon.

**Comment by trevorah** [comment]
Live now 🎉

**Comment by scriptnull** [comment]
@trevorah cool ! thanks.

**Pull request merged**
