### PR TITLE
Add Docker Hub integration

### PR DESCRIPTION
**Pull request by md5**

### CODE REVIEW

**Comment by md5** [comment]
One thing that I did not put in this PR was code to call back to Docker Hub at the `callback_url` to support [Webhook Chaining](http://docs.docker.com/docker-hub/builds/#webhook-chains).

The reason I didn't do this is that I wasn't sure what Gitter's policy was on having webhooks make outbound HTTP connections and I didn't find any existing webhook integrations in this repository doing so. I could imagine that making outbound HTTP connections could be restricted for security reasons.

**Comment by trevorah** [comment]
Hmm, this is the first time ive seen webhook chaining.

From the looks of things, this is meant for automated services in order to stop builds. But as long as we dont end up blocking a chain for someone we should be fine. This will be unlikely as docker hub supports repos defining multiple webhook chains.

As for our policy, Gitter integrations have been read only notifications for a while, mainly because:

1. thats what fits the activity feed (at the moment)
2. having a limited api interface makes supporting a range of third party services easier
3. as you mentioned, security is simpler

So yeah, no http requests for now.

**Comment by trevorah** [comment]
Your pull request is awesome btw, the only thing stopping me merging is the icons missing some height. They are currently 32x29 and 16x15 but need to be 32x32 and 16x16 respectively. I can update them for you if you like?

**Comment by md5** [comment]
I padded the icons out as requested. They were created from [this SVG](https://github.com/wesbos/Font-Awesome-Docker-Icon/blob/master/docker-white.svg) like so:

    convert -background transparent -antialias -resize 32x32 -extent 32x32 -gravity center \
        ~/Downloads/docker-white.svg lib/dockerhub/icons/logo@2x.png

I was just thinking it would be cool if `sanity.js` could check the icon sizes and file types, but that would involve adding `gm` or something similar in `devDependencies` for very little reason. Still, that sanity test was very helpful in creating a nice service, so it might be worth considering making it that much more robust. The only thing that makes me hesitate is that `gm` requires a separate install of GraphicsMagick or ImageMagick.

**Comment by mydigitalself** [comment]
https://github.com/netroy/image-size seems to be lighter weight?

**Comment by trevorah** [comment]
tbh i was thinking of ditching the image requirement altogether and to just use favicons. The only time any of the services use something other than their favicon are the ci services that just need a frowny face for failed builds.

**Comment by md5** [comment]
@mydigitalself Nice! I'll keep that one in mind for future reference.

**Comment by md5** [comment]
@trevorah Would you apply a `filter: grayscale(100%)` to them or something? Docker Hub's favicon is in color, as are many of the others.

**Comment by md5** [comment]
BTW, any idea when this change will go live? I'd like to hook it up to https://gitter.im/md5/docker-postgis

**Comment by trevorah** [comment]
Should be live within the next day or so. I'll give you a shout when its made it through.

As for the images, yeah, we would greyscale them. I was messing around a while back with trying to hue-rotate for error messages or something along those lines but like I said, turns out most services just use the same frowny face. Anything that we can do to cut down on the work involved in adding a service is fantastic imo.

**Comment by trevorah** [comment]
@md5 it should be live now. :sparkles:

Thanks for submitting this and enjoy your docker hub notifications!

**Comment by md5** [comment]
Nice! :rocket: 

I'll probably send another PR some time today to add a link to Docker Hub in `instructions.md`.

**Pull request merged**
