### PR TITLE
Add New Relic alerts support

### PR DESCRIPTION
**Pull request by ddfznt**

### CODE REVIEW

**Comment by trevorah** [comment]
Thanks @ddfznt! Have you tried it out in the playground to see if it works with real data?

**Comment by ddfznt** [comment]
Yeah! Example of an error a few minutes. (No app is perfect, right? :laughing: )
sem titulo

**Comment by trevorah** [comment]
Haha, awesome! I'll let you know when this is live.

**Comment by ddfznt** [comment]
:facepunch: :raised_hands:

**Comment by trevorah** [comment]
@ddfznt It's live!

**Pull request merged**
