### PR TITLE
Add support for Coveralls

### PR DESCRIPTION
**Pull request by alexfu**
This should take care of #31

### CODE REVIEW

**Comment by trevorah** [comment]
Sorry about the wait, there was a chocolate coma epidemic. I'll take a look at this today.

**Comment by trevorah** [comment]
Can you confirm that you have tested this against the actual coveralls website?

**Comment by alexfu** [comment]
@trevorah yes, i've tested it with the actual website.

**Comment by trevorah** [comment]
Awesome.

**Comment by trevorah** [comment]
Thank you so much, @alexfu. This should be live in the next day or so.

**Pull request merged**
