### PR TITLE
Doorbell.io integration

### PR DESCRIPTION
**Pull request by manavo**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
:+1:

**Comment by trevorah** [comment]
Have you tried using the playground with doorbell.io?

The [doorbell.io webhook examples](https://doorbell.io/docs/webhooks) dont look much like the ones in your pull request...
```json
{
    "event": "new-feedback",
    "data": {
        "id": 467,
        "email": "phil@doorbell.io",
        "url": "https:\/\/doorbell.io\/applications\/15\/feedback\/467",
        "member": {
            "id": 168,
            "name": "Jimbo",
            "email": "jimbo@example.com"
        },
        "user_agent": "Chrome 43.0.2357.124 on Macintosh",
        "parsed_user_agent": {
            "platform": "Macintosh",
            "browser": "Chrome",
            "version": "43.0.2357.124"
        },
        "message": "Here is the feedback that the user sent",
        "sentiment": "positive",
        "application": {
            "id": 15,
            "name": "Your Application Name"
        },
        "created_at": "2015-06-24 11:42:22"
    }
}
```

**Comment by manavo** [comment]
Hey @trevorah! From Doorbell's side it actually does all the customising and just sends a 'message'. I already had all the logic for creating the formatted markdown message for other chat systems, so it was easier than creating the messages here from the raw webhooks!

**Comment by trevorah** [comment]
Ah, that makes sense. I'll try and get this live today!

**Comment by manavo** [comment]
Awesome! Thanks for the quick reply Andy! :+1:

**Comment by eddiejaoude** [comment]
Great work, thanks all - looking forward to this :+1:

**Comment by trevorah** [comment]
Its live! :tada:

**Comment by manavo** [comment]
:tada: :shipit: :tada:

**Comment by manavo** [comment]
And Gitter is now promoted on Doorbells' homepage as an integration :)

https://doorbell.io/

**Comment by trevorah** [comment]
sweet!

**Comment by eddiejaoude** [comment]
Integrated! :smile:

**Pull request merged**
