### PR TITLE
updated Drone implementation to use new Gitter plugin

### PR DESCRIPTION
**Pull request by bradrydzewski**
A few weeks ago we released a new version of Drone and introduced a revamped Gitter plugin and need to update the service integration accordingly. Note that the integration is greatly simplified because the Drone plugin does all the heavy lifting and sends Gitter the exact payload required to render an activity item.

I can confirm integration tests (posting to the playground via localtunnel.me) produces a valid activity message and no mangled urls :smile: 

Let me know if you have any questions or comments. Thanks!

### CODE REVIEW

**Comment by daMupfel** [comment]
maybe say that it needs drone  version >=0.4

**Comment by tboerger** [comment]
Awesome, really simple and future proof for drone!
:+1:

**Comment by trevorah** [comment]
Sorry about the wait!

Wouldnt this break for existing subscriptions? If someone has set up a webhook in the old generic way, then this new parser will expect the special gitter payload, but receive the old generic payload and then break.

**Comment by bradrydzewski** [comment]
@trevorah yes this will break existing subscriptions _this time_. The 0.3 version of Drone is end of life and not supported. It was an alpha release and there were major breaking changes when 0.4 beta was release.

Going forward breaking changes will not be an issues because:

1. plugins are versioned
2. plugins auto-upgrade
3. our Gitter plugin transforms data locally which, as you can see, means future changes to the Drone plugin will no longer impact Gitter

**Comment by trevorah** [comment]
Thats good for the future, but Im really against breaking the integration for the ~140 rooms that use this. Im happy with removing support for the old version of drone in the future, but there really should be a transitional period. I would suggest looking for the `message` key in the json payload and defaulting to the old function if it doesnt exist.

**Comment by tboerger** [comment]
@trevorah but the old drone version reached anyway EOL, so it's unsupported.

**Comment by trevorah** [comment]
@tboerger sure, but people are still using the old webhook. We cant break existing integrations without a warning or a simple upgrade path for our users. Its just not cool.

**Comment by trevorah** [comment]
@bradrydzewski i've copied the content of your pr and tweaked it so that we still support the old webhooks. Are you ok with this?

**Comment by tboerger** [comment]
Awesome

**Comment by trevorah** [comment]
@bradrydzewski I'll go ahead with it for now, let me know if you want it changed.

**Comment by trevorah** [comment]
Its now live.

**Comment by tboerger** [comment]
:dancers:

**Pull request closed without merging**
